[workspace]
resolver = "2"
members = [
    "abc044",
    "abc049",
    "abc058",
    "abc071",
    "abc081",
    "abc083",
    "abc086",
    "abc087",
    "abc090",
    "abc092",
    "abc093",
    "abc094",
    "abc100",
    "abc101",
    "abc102",
    "abc115",
    "abc116",
    "abc121",
    "abc122",
    "abc132",
    "abc136",
    "abc138",
    "abc139",
    "abc142",
    "abc143",
    "abc150",
    "abc156",
    "abc157",
    "abc160",
    "abc161",
    "abc170",
    "abc176",
    "abc190",
    "abc200",
    "abc210",
    "abc220",
    "abc221",
    "abc229",
    "abc240",
    "abc280",
    "abc318",
    "abc339",
    "abc349",
    "abc350",
    "abc362",
    "template",
]
