[workspace]
resolver = "2"
members = [
    "abc058",
    "abc086",
    "abc087",
    "abc090",
    "abc092",
    "abc093",
    "abc094",
    "abc100",
    "abc101",
    "abc102",
    "abc121",
    "abc122",
    "abc132",
    "abc136",
    "abc138",
    "abc139",
    "abc142",
    "abc143",
    "abc156",
    "abc157",
    "abc160",
    "abc161",
    "abc170",
    "abc200",
    "abc220",
    "abc339",
    "abc362",
    "template",
]
